version: '3'
services:
  react_front_end:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3000
    volumes:
      - /app/node_modules
      - .:/app
  testing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    